import { StyleSheet } from "react-native";

export const colors = {
  background: "#004797ff",
  header: "#003a77ff",
  surface: "#0066ffff",
  primary: "#0052cdff",
  text: "#ffffff",
  textSecondary: "#c9d5edff",
  alert: "#D32F2F",
  accent: "#6e90b7ff",
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingVertical: 60,
    paddingHorizontal: 20,
    color: "white",
    height: "100%",
  },
  card: {
    backgroundColor: colors.header,
    padding: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "flex-start",
    marginTop: 10,
  },
  previewCard: {
    backgroundColor: colors.header,
    padding: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "flex-start",
    marginVertical: 10,
    gap: 10,
  },
  previewCardImage: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    backgroundColor: "#2660adff",
  },

  title: {
    fontSize: 28,
    paddingTop: 20,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 10,
  },
  subTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: 10,
  },
  text: {
    fontSize: 14,
    color: colors.textSecondary,
    alignItems: "flex-start",
    marginTop: 10,
  },
  input: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.textSecondary,
    alignItems: "flex-start",
    marginTop: 10,
  },
  centeredContainer: {
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    height: "100%",
    marginVertical: 100,
  },
  header: {
    flexDirection: "row",
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 10,
    gap: 10,
  },
  date: {
    paddingHorizontal: 5,
    alignItems: "flex-end",
    fontWeight: "bold",
    fontSize: 16,
    color: colors.text,
  },
  button: {
    backgroundColor: colors.primary,
    padding: 15,
    paddingHorizontal: 20,
    color: colors.textSecondary,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
  },
  empty: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    backgroundColor: colors.accent,
    borderRadius: 10,
    width: "100%",
    height: "100%",
    color: "white",
    fontWeight: "bold",
    marginTop: 20,
  },
  pickerItem: {
    color: "white",
  },
  pickerContainer: {
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 20,
    marginTop: 200,
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  picker: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    alignItems: "flex-start",
    rowGap: 10,
    gap: 10,
  },
  gridItem: {
    width: 150,
    height: 150,
    marginVertical: 30,
    borderRadius: 10,
    backgroundColor: colors.header,
  },
});
